%YAML:1.0

#common parameters
imu_topic: "/imu/data"
image_topic: "/camera/color/image_raw"
output_path: "/home/seu/xjl_work_space/gvins_yolo_ws/output/"

#camera calibration 
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: 0.0
   k2: 0.0
   p1: 0.0
   p2: 0.0
projection_parameters:
   fx: 952.011
   fy: 959.650
   cx: 661.733
   cy: 375.598
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [-3.2304155944709256e-02, 2.0440273741593401e-01,  9.7835370007251121e-01,
        -9.9940319216271267e-01,    5.3768825030693357e-03, -3.4122553092180485e-02,
             -1.2235236151395545e-02, -9.7887211119299011e-01,  2.0410705260940532e-01]


extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [ -5.0556170302897635e-02, -6.6259979723923099e-02, 8.5566524781577821e-03  ]


#feature traker paprameters
max_cnt: 500           # max feature number in feature tracking
min_dist: 18            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.20  # max solver itration time (ms), to guarantee real time
max_num_iterations: 20   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.002         # accelerometer measurement noise standard deviation. #0.2   0.04                0.02
gyr_n: 0.008         # gyroscope measurement noise standard deviation.     #0.05  0.004              0.0008
acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.02    0.00004   0.00002
gyr_w: 0.0002      # gyroscope bias random work noise standard deviation.     #4.0e-5     2.0e-6     2.0e-6
g_norm: 9.81007     # gravity magnitude

#loop closure parameters
loop_closure: 1                    # start loop closure
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project
pose_graph_save_path: "/home/seu/xjl_work_space/gvins_yolo_ws/output/" # save and load path

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet). 

#visualization parameters
save_image: 1                   # save image in pose graph for visualization prupose; you can close this function by setting 0 
visualize_imu_forward: 0        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ

#gvins_parameters
gnssthreshold: 20
imudatarate: 200
minmum_align_velocity: 0.3
estimate_sign: 0
antlever: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.03, 0, -0.3] 
#data: [0.01,0.202,0.003]
sign_closure: 0                    # start sign closure
groundtruth_file: "/home/seu/parking1.txt" # load path